=== pepebsd/MGTest/src/main/java/es/tragsatec/pssa/utilidades/poliza.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


<!--  definicion de elementos simples -->


    <xs:element name="plan"  type="planType"/>
    <xs:element name="numLiquidacion" type="numLiquidacionType"/>
    <xs:element name="tipoSeguro" type="tipoSeguroType"/>
    <xs:element name="fechaLiquidacion" type="fechaLiquidacionType"/>
    <xs:element name="nifTomador" type="stringtype"/>
    
    <xs:element name="refColectivo" type="stringtype"/>
    <xs:element name="digitoControlColectivo" type="stringtype"/>
    <xs:element name="linea" type="stringtype"/>
    <xs:element name="codEntidadAseguradora" type="stringtype"/>
    
    
    
    

  <xs:element name="polizas"> 

<!--  definicion de elementos complejos -->
<xs:element name="faseLiquidacion"><!--    type="xs:faseLiquidacionType"/> -->
  <xs:complexType>
  <xs:sequence>
    <xs:element ref="plan"/>
    <xs:element ref="numLiquidacion"/>
    <xs:element ref="tipoSeguro"/>
    <xs:element ref="fechaLiquidacion"/>
    <xs:element ref="tomador"/>
    </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="tomador">
  <xs:complexType>
  <xs:sequence>
    <xs:element ref="nifTomador"/>
    <xs:element ref="colectivo"/>
    </xs:sequence>
    </xs:complexType>
</xs:element>


<xs:element name="colectivo">
  <xs:complexType>
  <xs:sequence>
    <xs:element ref="refColectivo"/>
    <xs:element ref="digitoControlColectivo"/>
    <xs:element ref="linea"/>
    <xs:element ref="codEntidadAseguradora"/>
    </xs:sequence>
    </xs:complexType>
</xs:element>




<!-- definicion de tipos simples con validacion -->
<xs:simpleType name="stringtype">
  <xs:restriction base="xs:string"/>
</xs:simpleType>

<xs:simpleType name="inttype">
  <xs:restriction base="xs:positiveInteger"/>
</xs:simpleType>

<xs:simpleType name="dectype">
  <xs:restriction base="xs:decimal"/>
</xs:simpleType>

<xs:simpleType name="polizaId">
  <xs:restriction base="xs:string">
    <xs:pattern value="[0-9]{4}"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="polizaIdType">
  <xs:restriction base="xs:string">
    <xs:pattern value="[0-9]{6}"/>
  </xs:restriction>
</xs:simpleType>



<!-- tipos de datos de faseLiquidacionType-->
<xs:simpleType name="planType">
  <xs:restriction base="xs:positiveInteger">
    <xs:pattern value="[0-9]{4}"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="numLiquidacionType">
  <xs:restriction base="xs:positiveInteger">
    <xs:pattern value="[0-9]{4}"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="tipoSeguroType">
  <xs:restriction base="xs:string">
    <xs:pattern value="[A-Z]{1}"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="fechaLiquidacionType">
  <xs:restriction base="xs:date">
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="tomadorType">
  <xs:sequence>
    <xs:element name="nifTomador" type="nifTomadorType"/> <!--  9digitos, la prim num, X, L o M,
    													despues entre 0 y 7 digitos
    													el ultimo caracter es letra mayuscula -->
 	<xs:element name="nombreTomador" type="stringtype"/>

    </xs:sequence>
    </xs:complexType>

<!--   <xs:attribute name="polizaId" type="polizaIdType" use="required"/> -->
<xs:simpleType name="nifTomadorType">
  <xs:restriction base="xs:string">
    <xs:pattern value="[0-9,A-Z]{9}"/>
  </xs:restriction>
</xs:simpleType>



</xs:schema>

=== pepebsd/MGTest/src/main/java/es/tragsatec/pssa/utilidades/poliza.xml
<?xml version="1.0" encoding="UTF-8"?>

<polizas orderid="889923" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="poliza.xsd">
<!--   <orderperson>John Smith</orderperson>  -->
<faseLiquidacion>
<plan>2020</plan>
<!--  entero 4 digitos  -->
<numLiquidacion>1234</numLiquidacion>
<!--  entero 1 a 4 digitos  -->
<tipoSeguro>A</tipoSeguro>
<!--  Alfanumerico 1 digito [A] -> Agricola  -->
<fechaLiquidacion>2022-02-02</fechaLiquidacion>
<!--  Fecha ISO  -->
</faseLiquidacion>
<tomador>
<nifTomador>06997121P</nifTomador>
<refColectivo>121</refColectivo>
</tomador>
<tomador>
<nifTomador>06997122P</nifTomador>
<refColectivo>122</refColectivo>
</tomador>
<tomador>
<nifTomador>06997123P</nifTomador>
<refColectivo>123</refColectivo>
</tomador>
<tomador>
<nifTomador>06997124P</nifTomador>
<refColectivo>124</refColectivo>
</tomador>
<tomador>
<nifTomador>06997125P</nifTomador>
<refColectivo>125</refColectivo>
</tomador>
<tomador>
<nifTomador>06997126P</nifTomador>
<refColectivo>126</refColectivo>
</tomador>
<colectivo>
<refColectivo>121</refColectivo>
<digitoControlColectivo>1</digitoControlColectivo>
<linea>41</linea>
<codEntidadAseguradora>145</codEntidadAseguradora>
</colectivo>
<colectivo>
<refColectivo>122</refColectivo>
<digitoControlColectivo>2</digitoControlColectivo>
<linea>42</linea>
<codEntidadAseguradora>245</codEntidadAseguradora>
</colectivo>
<colectivo>
<refColectivo>123</refColectivo>
<digitoControlColectivo>3</digitoControlColectivo>
<linea>43</linea>
<codEntidadAseguradora>345</codEntidadAseguradora>
</colectivo>
</polizas>
